### PR TITLE
Sl fixes

### PR DESCRIPTION
**Pull request by ahliang51**
# Types of changes in this PR

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change of an existing feature
- [ ] Refactor/Performance enhancements
- [ ] Infra/Config changes

# Overview (attach screenshots if necessary)

- Fix Comment Section (2h)
- Apply button for Volunteer/Job application for Listings (3h)

@Kalsyc

### CODE REVIEW

**Comment by Kalsyc** [comment]
Looks good but actually should we place a confirmation for the user before they send the email?
In hindsight, I think it might be good to have that confirmation first. (I think eventually we'll place a card stating more info about the job or what the listing might require from the user applying)

@ahliang51

**Comment by ahliang51** [comment]
@Kalsyc all right sounds good, will work on it

**Comment by ahliang51** [comment]
@Kalsyc added confirmation popup. Do take a look

**Review by Kalsyc — APPROVED** [review]
Nice work LGTM 👍🏻

**Pull request merged**
